### PR TITLE
Added Dark Mode Toggle button

### PR DESCRIPTION
**Pull request by Hemashree21**
Resolved issue #213 

image

@Priyaaa1 please check and let me know if there are any changes

### CODE REVIEW

**Comment by Priyaaa1** [comment]
@Hemashree21 kindly resolve conflicts

**Comment by Hemashree21** [comment]
@Priyaaa1 resolves

**Comment by Priyaaa1** [comment]
@Hemashree21 conflicts are there

**Comment by Hemashree21** [comment]
@Priyaaa1 Now it's resolved

image

**Comment by Hemashree21** [comment]
@Priyaaa1 can you please check and merge the pr mam?

**Pull request closed without merging**
