### PR TITLE
Added the github icon

### PR DESCRIPTION
**Pull request by pani2004**
Solved issue #388 
Screenshot (47)

### CODE REVIEW

**Comment by pani2004** [comment]
@Priyaaa1 Pls review the PR!!!

**Comment by Priyaaa1** [comment]
@pani2004 it would be better if the GitHub icon will lead to this repo, not my profile

**Comment by pani2004** [comment]
Ok @Priyaaa1 will make the changes

**Comment by pani2004** [comment]
@Priyaaa1 Made the changes!!

**Review by Priyaaa1 — APPROVED** [review]

**Pull request merged**
