### PR TITLE
Enhanced FAQ section with icons and smooth scrolling

### PR DESCRIPTION
**Pull request by govindumeesala**
### Description

**This PR enhances the FAQ section by introducing two main improvements:**

1. **Smooth Scroll Effect:** Implemented smooth scrolling when an FAQ question is clicked, providing a better user experience.
2. **Rotating Arrow Icon:** Added a rotating effect to the arrow icon beside each FAQ question to indicate whether the answer is expanded or collapsed.

**Fixes:** #214

**Implementation Details**:

- Utilized useRef and useEffect hooks to dynamically calculate the content height and apply smooth scrolling.
- Applied CSS transitions for smooth opening and closing of FAQ answers.
- The arrow icon rotates smoothly to indicate the open or close state.

**Changes Made:**

- Added dynamic content height calculation using useRef and useEffect.
- Implemented smooth transitions for FAQ answers using CSS max-height, padding, border, and margin transitions.
- Included arrow icon rotation using transform and transition.

image

@Priyaaa1, could you please review this PR and merge it if everything looks good? Thanks!

### CODE REVIEW

**Comment by Priyaaa1** [comment]
@govindumeesala your code changes direction of the website logo

**Comment by govindumeesala** [comment]
> @govindumeesala your change rotated the website logo too

My bad, did not notice it. I will work on it. Thanks for reminding me.

**Comment by govindumeesala** [comment]
@Priyaaa1 
I have addressed the issue where the logo in the navbar was rotating along with the FAQ icon. This happened because I used the class name 'active' for faq icons which is already being used by logo. I have now changed the class name for the FAQ icon to 'active-faq' to prevent this conflict.

Everything is set and ready to go. Please review the PR once more.

Thank you!

**Comment by sahil10023** [comment]
Priya mam in this merging please check that the issue that i fixed of testimonial Card overlpaing The ChatBot is not fixed . i Dont khow that Either it is Due to govindumeesala Sir Forgot to pull the Latest Main Stream. I am Informing You Because the issue that i fixed in #226 is not Fixed in Latest main Steam. Please govindumeesala sir and Priya mam Don't Get angry on me i am just telling because my fixes were not present in main Stream.

**Comment by govindumeesala** [comment]
> Priya mam in this merging please check that the issue that i fixed of testimonial Card overlpaing The ChatBot is not fixed . i Dont khow that Either it is Due to govindumeesala Sir Forgot to pull the Latest Main Stream. I am Informing You Because the issue that i fixed in #226 is not Fixed in Latest main Steam. Please govindumeesala sir and Priya mam Don't Get angry on me i am just telling because my fixes were not present in main Stream.

I think I made sure that I pulled from main branch before sending pr, but again I apologize if it's my fault. Now I've checked and the issue with testimonial Card overlpaing The ChatBot is fixed.

**Comment by sahil10023** [comment]
Actually the issue is not yet fixed what this is the main stream at current time 

Screenshot 2024-05-23 105212


and you can check my priview of deployement in #226 

Screenshot 2024-05-23 105212


so in the end now Only Priya mam can Fix this issue.

**Pull request merged**
