### PR TITLE
solved issue dark mode and light mode

### PR DESCRIPTION
**Pull request by nikhildeshmukh170**
solved issue dark mode and light mode

- [X]  bug fix
- [X]  Now it's ready for merge.

video:

https://github.com/Priyaaa1/StartConnect-Hub/assets/115735153/ff65e17a-cc50-4ed1-8f98-cd5f04471d93

I'm a GSSOC Contributor.

### CODE REVIEW

**Comment by nikhildeshmukh170** [comment]
@Priyaaa1 please merge it.

**Comment by Priyaaa1** [comment]
@nikhildeshmukh170 kindly mention the issue that you resolved.

**Comment by nikhildeshmukh170** [comment]
ISSUE NUMBER- #531

**Comment by Priyaaa1** [comment]
@nikhildeshmukh170 this issue is not assigned to you

**Comment by nikhildeshmukh170** [comment]
@Priyaaa1 assign me this issue

**Comment by Priyaaa1** [comment]
@nikhildeshmukh170 comment in that issue for the assignment, so that I can assign you.

**Comment by Priyaaa1** [comment]
issue #612

**Comment by nikhildeshmukh170** [comment]
@priyaaa1 please update level

**Pull request merged**
