### PR TITLE
Update Footer.jsx

### PR DESCRIPTION
**Pull request by Meetjain1**
### Description:
This PR enhances the footer section of the website by adding the current copyright year, which is fetched dynamically. This ensures that the copyright year will always be up-to-date without requiring manual updates each year.

#### Changes:
1. **Footer HTML**: Updated the footer to include a placeholder for the copyright year.
2. **JavaScript**: Added a script to fetch the current year dynamically and insert it into the footer.
3. **CSS**: Ensured that the styling of the footer remains consistent with the new dynamic content.

#### Benefits:
- **Automation**: The copyright year updates automatically, reducing maintenance overhead.
- **Accuracy**: Ensures the displayed year is always current, improving the website's professionalism.

### CODE REVIEW

**Comment by Priyaaa1** [comment]
@Meetjain1 if you haven't assigned the issue for this, you'll not get any points in GSSoC'24.

**Comment by Meetjain1** [comment]
> @Meetjain1 if you haven't assigned the issue for this, you'll not get any points in GSSoC'24.

I have raised issue please assign and add gssoc level . Thanks @Priyaaa1 
closes #664

**Comment by MastanSayyad** [comment]
Hey @Meetjain1 there is only one minor change, I can only give you gssoc label

**Comment by MastanSayyad** [comment]
I have talked with sanjay,  as per gssoc guidelines I can only give you gssoc label, However if you can implement dynamic date functionality updating monthly to the Legel pages(Privacy, Terms) and yearly for licensing page then I can label you level 2 for it @Meetjain1

**Comment by Meetjain1** [comment]
> I have talked with sanjay, as per gssoc guidelines I can only give you gssoc label, However if you can implement dynamic date functionality updating monthly to the Legel pages(Privacy, Terms) and yearly for licensing page then I can label you level 2 for it @Meetjain1

Ok @MastanSayyad enabling this and raising Pr .

**Comment by MastanSayyad** [comment]
Yeah @Meetjain1, Also please make sure you raise an Issue first and only raise the PR when the issue got assigned to you! as @Priyaaa1 mentioned above "if you haven't assigned the issue for this, you'll not get any points in GSSoC'24."

At least in this repository, we follow the guidelines and instructions provided by the `gssoc` unlike other repos.

**Pull request merged**
