### PR TITLE
login and signup page

### PR DESCRIPTION
**Pull request by Yashop181**
Added a label to the login page and fixed the alignment of the "Sign in with Google" button on the signup page.

Added a label element and adjusted CSS for alignment. 

Screenshots are attached for reference:

SignUp:-
Screenshot (1235)

Login:-
Screenshot (1236)

### CODE REVIEW

**Comment by Priyaaa1** [comment]
@Yashop181 the login with google button should be same in login page ang signup page.

**Comment by Yashop181** [comment]
Sure, @Priyaaa1 I'll make sure the "Login with Google" button is consistent on both the login and signup pages.

**Comment by Yashop181** [comment]
Hi @Priyaaa1 , I’ve completed the updates and ensured that the "Login with Google" button is consistent on both the login and signup pages. Please see the screenshot below for verification:


Screenshot (1241)

Screenshot (1240)

Let me know if everything looks good!

**Comment by MastanSayyad** [comment]
@Yashop181 What's the difference between PR #655 and #657, I see no difference

**Pull request closed without merging**
