### PR TITLE
Resolving Conflict and Refactoring

### PR DESCRIPTION
**Pull request by codewithmurali**
### Changes Made:

- [x] #418  Resolved a conflict in the package.json file.
- [x] Uninstalled the react-google-button package to streamline dependencies.

### Fixed these issues encountered during development:

- [x] Corrected import statements for createContext.
- [x] Adjusted the naming of the import path for privacy policy.
- [x] Updated the property assignment in the Testimonial component class to className.

### CODE REVIEW

**Comment by Priyaaa1** [comment]
@codewithmurali deployment preview isn't there

**Review by Priyaaa1 — APPROVED** [review]

**Comment by rohitroy-github** [comment]
@Priyaaa1 is the issue fixed, the site's still not active ?

**Comment by Priyaaa1** [comment]
@rohitroy-github now it's working

**Comment by rohitroy-github** [comment]
Yeah. Cool.

**Pull request merged**
