### PR TITLE
[Feature] : Navbar add close icon

### LINKED ISSUE #568: [Feature] : `Navbar` add close icon
- In this project mobile site `menu` open icon click after add close icon .
- please assign me ...

### Screen Shot

[Screencast from 2024-06-30 17-20-50.webm](https://github.com/Priyaaa1/StartConnect-Hub/assets/121082414/85592267-e16d-4bb9-8e6c-5dbdbb69d985)

### My solution

[Screencast from 2024-06-30 16-43-34.webm](https://github.com/mdazfar2/HelpOps-Hub/assets/121082414/2afd6005-294e-4ad0-9ff0-b63cf721010e)

### PR DESCRIPTION
**Pull request by sivaprasath2004**
Hello @Priyaaa1 

closes #568 

- I will finish it..
- please merge it 

### Before

[Screencast from 2024-06-30 17-20-50.webm](https://github.com/Priyaaa1/StartConnect-Hub/assets/121082414/85592267-e16d-4bb9-8e6c-5dbdbb69d985)

### After

[Screencast from 2024-07-09 12-37-42.webm](https://github.com/Priyaaa1/StartConnect-Hub/assets/121082414/43978bdb-4350-47b6-b28f-6350cb0af761)

### CODE REVIEW

**Comment by Priyaaa1** [comment]
@sivaprasath2004 the hamburger menu isn't working. Also, it's visible in larger screens too.

**Comment by sivaprasath2004** [comment]
[Screencast from 2024-07-09 21-18-15.webm](https://github.com/Priyaaa1/StartConnect-Hub/assets/121082414/7c2b06a0-cc86-4aa8-9c8b-a973250b71b8)

@Priyaaa1 fixed ..
please merge this..

**Comment by Priyaaa1** [comment]
@sivaprasath2004 the hamburger icon is not working on clicking.

**Comment by Priyaaa1** [comment]
@sivaprasath2004 the issue has been resolved now by someone else.

**Pull request closed without merging**
