### PR TITLE
Fix issue #173

### LINKED ISSUE #173: Hamburger icon needs to be visible in mobile view
**Is your feature request related to a problem? Please describe.**

Hamburger icon needs to be visible in mobile 
Screenshot_20240519_181856

**Describe the solution you'd like**

**Additional context**

### PR DESCRIPTION
**Pull request by kapilG0**
I have fixed that issue #173 and I raised that issue #174  as well I know it is not assigned but I have to work on that to fix #173. I tested on my side .
image

### CODE REVIEW

**Comment by Priyaaa1** [comment]
@kapilG0 your code makes changes in Footer

**Comment by kapilG0** [comment]
> @kapilG0 your code makes changes in Footer

@Priyaaa1 for mobile mode it is showing like this and for desktop it is the same way as it was showing

**Comment by kapilG0** [comment]
> > @kapilG0 your code makes changes in Footer
> 
> @Priyaaa1 for mobile mode it is showing like this and for desktop it is the same way as it was showing

Hello @Priyaaa1 if there any modifications required please let me know I will try to do that. Please let me know thank you

**Comment by kapilG0** [comment]
Hello @Priyaaa1 can you please close issue #173 as pr #201 has merged for that issue.

**Pull request merged**
