### PR TITLE
Added "Guided Conversation" Functionality to the Chatbot 

### LINKED ISSUE #613: [Feature]: Add guided conversation functionality to Chatbot
**Is your feature request related to a problem? Please describe.**
When we ask something to the chatbot, it fails to answer most questions. It can only handle questions which is known to it. 

**Describe the solution you'd like**
We can present users with a predefined set of questions or options they can choose from. This improves the conversation and reduces the chances of the chatbot encountering unanswerable questions.

### PR DESCRIPTION
**Pull request by MastanSayyad**
Hey @Priyaaa1 
- Issue Fixes #613

I have added the guided functionality to the chatbot with predefined options and action handles

**Files Changed:**
- `ActionProvider.jsx`
- `MessageParser.jsx`
- `config.jsx`
- `ChatAssistant.css`

**Files Created:**
- `Options.jsx`
- `utils.jsx`

**Changes I made:**
- Made changes in `ActionProvider.jsx`, Added new action handlers for `Options` `handleHell`, `handleThank`, `defaultResponse`.
- Updated existing action handlers for improved functionality.
- `MessageParser.jsx`: Enhanced message parsing logic for specific user queries.
- Fixed issues with default responses and handling of gratitude messages.
- Created `Options.jsx` and added dedicated predefined options
- `config.jsx` Updated configuration to integrate new actions and ensure compatibility with the updated message handling.
- Created `utils.jsx` and Added `shuffleArray` function to shuffle options dynamically.

image

https://github.com/user-attachments/assets/7293d8ad-0074-4cc2-b30e-9165e49cbd6f

### CODE REVIEW

**Comment by MastanSayyad** [comment]
Hey @Priyaaa1 Please take a look and merge this PR!

**Comment by MastanSayyad** [comment]
Hey @Priyaaa1 pls merge this PR as the gssoc is near to its end!

**Comment by Priyaaa1** [comment]
@MastanSayyad it is giving 2 same options for Contact, and it must be showing what option we have chosen.

image

**Comment by MastanSayyad** [comment]
Hey @Priyaaa1 dont worry about it, the options shuffle after each question being answered, so this is the least possibility to be noticed!

**Pull request merged**
