### PR TITLE
Creating a Startups Page

### PR DESCRIPTION
**Pull request by avanimathur**
Issue #368 

@Priyaaa1 Please review the changes and merge if applicable.

This is under GSSOC'24.

### CODE REVIEW

**Comment by Priyaaa1** [comment]
@avanimathur it's showing a blank page on clicking on investor management

**Comment by Priyaaa1** [comment]
@avanimathur are you working on it to fix this?

**Comment by avanimathur** [comment]
Yes, please allow me some more time.
I'll make the required changes.

**Comment by avanimathur** [comment]
I have submitted a new PR #571

**Comment by avanimathur** [comment]
@Priyaaa1 I have submitted a new PR #571 as this one had merge conflicts

**Pull request closed without merging**
