### PR TITLE
Fixed the Navbar and LoginPage

### PR DESCRIPTION
**Pull request by Harsha19-08**
Fixed the Issue #335 
Fixed the Nav Css of Login and Added the Login Page Animatedly 
image

@Priyaaa1 As It was Assigned check the PR and  merge the PR under GSSOC level 3.

### CODE REVIEW

**Comment by Priyaaa1** [comment]
@Harsha19-08 kindly resolve conflicts

**Comment by Priyaaa1** [comment]
@Harsha19-08 deploy preview isn't there

**Comment by Priyaaa1** [comment]
@Harsha19-08 kindly resolve conflicts

**Comment by Harsha19-08** [comment]
@Priyaaa1 can u check it the pr

**Comment by Priyaaa1** [comment]
@Harsha19-08 conflicts are there

**Comment by Priyaaa1** [comment]
@Harsha19-08 kindly resolve conflicts at the earliest.

**Comment by Harsha19-08** [comment]
I am trying to resolve the conflicts as it was running locally very perfectly.....

**Pull request closed without merging**
