### PR TITLE
feat/navbar hover added

### LINKED ISSUE #46: Change hover of navbar..

### PR DESCRIPTION
**Pull request by drick-infinity**
#46 Change hover of navbar and buttons are done.
fixes #46 
under gssoc'24

better enhancement in navbar hover 

https://github.com/Priyaaa1/StartConnect-Hub/assets/116994649/110411ce-efd4-4cf3-a9df-19e9297823d1

### CODE REVIEW

**Comment by Priyaaa1** [comment]
@drick-infinity it's not looking fine

**Comment by Priyaaa1** [comment]
@drick-infinity you'll not get any points as the task wasn't assigned to you

**Comment by drick-infinity** [comment]
As I see this issue is open for more than 2 days so I contribute as open source in gssoc'24 If you want some changes to add new hover effect I surrely do this.

**Comment by drick-infinity** [comment]
can you assign this issue to me to get change and the points count under gssoc'24

**Comment by Priyaaa1** [comment]
@drick-infinity but the changes you did aren't making navbar look better

**Comment by RishabhDhawad** [comment]
@drick-infinity  there are some merge conflicts in the following file first resolve those and push your code again creating another PR as I am closing this one.

**Pull request closed without merging**
