### PR TITLE
Feat stripe payment invest 

### PR DESCRIPTION
**Pull request by Anushkajoshii**
issue:- [Feature Request]: Stripe-Payment Integration for invest option #639

### CODE REVIEW

**Comment by MastanSayyad** [comment]
Hey @Anushkajoshii The changes are too complex to avoid any breaking code can you pls provide snapshots and screen record of the changes?

**Comment by Anushkajoshii** [comment]
@MastanSayyad here are the snaps of the changes:
These are the files list:-

Screenshot 2024-08-01 at 6 38 14 PM


And here is the screen recording of codes being changed:-


Screenshot 2024-08-01 at 8 01 20 PM
Screenshot 2024-08-01 at 8 01 52 PM




https://github.com/user-attachments/assets/81100a00-5807-4e6d-b534-dca052956030


https://github.com/user-attachments/assets/b8de8430-117e-4dfd-888e-6682fa909dee

**Comment by Anushkajoshii** [comment]
@MastanSayyad here are the snaps of the changes:
These are the files list:-

Screenshot 2024-08-01 at 6 38 14 PM


And here is the screen recording of codes being changed:-


Screenshot 2024-08-01 at 8 01 20 PM
Screenshot 2024-08-01 at 8 01 52 PM




https://github.com/user-attachments/assets/81100a00-5807-4e6d-b534-dca052956030


https://github.com/user-attachments/assets/b8de8430-117e-4dfd-888e-6682fa909dee

**Comment by Anushkajoshii** [comment]
@MastanSayyad here are the snaps of the changes:
These are the files list:-

Screenshot 2024-08-01 at 6 38 14 PM


And here is the screen recording of codes being changed:-


Screenshot 2024-08-01 at 8 01 20 PM
Screenshot 2024-08-01 at 8 01 52 PM
Screenshot 2024-08-01 at 8 03 00 PM

Screenshot 2024-08-01 at 8 03 24 PM


https://github.com/user-attachments/assets/b8de8430-117e-4dfd-888e-6682fa909dee


These are packages and lock files:-

https://github.com/user-attachments/assets/3e977286-3336-47aa-9486-39e03155cb6e

**Comment by MastanSayyad** [comment]
Hey @Anushkajoshii I mean the work you have done, show snapshots of working Output

**Comment by Anushkajoshii** [comment]
@MastanSayyad Here is the output

Screenshot 2024-07-21 at 7 32 16 PM
Screenshot 2024-07-21 at 7 33 44 PM
Screenshot 2024-07-21 at 7 33 53 PM
Screenshot 2024-07-21 at 7 34 12 PM


https://github.com/user-attachments/assets/94f821c2-4254-4fd3-b048-85917a180494

**Comment by MastanSayyad** [comment]
@Anushkajoshii Please resolve the conflicts

**Comment by MastanSayyad** [comment]
Hey @Anushkajoshii Let's wait till the admin review your PR as you have integrated backend!

**Comment by Priyaaa1** [comment]
@Anushkajoshii it isn't working. Kindly make raise another PR for this after resolving things.

**Pull request merged**
