### PR TITLE
Added hovering effect on the footer

### PR DESCRIPTION
**Pull request by namandude**
Hey !!
I resolved the issue no. #327 . 
Website already looks amazing , i added a pinch  of hovering effect in the footer section which makes it looks more appealing.
I added in both the dark and light mode .
From :
Screenshot 2024-06-05 125024

Screenshot 2024-06-05 125159

To :
Screenshot 2024-06-05 125032
Screenshot 2024-06-05 125137

Thank You ! Hope u like this.

### CODE REVIEW

**Comment by namandude** [comment]
Hey can you please review it.

**Review by Priyaaa1 — APPROVED** [review]

**Comment by Priyaaa1** [comment]
@namandude kindly resolve conflicts

**Comment by namandude** [comment]
Hey please check i commit it again

**Comment by namandude** [comment]
Hey @Priyaaa1 Please do check it now

**Review by Priyaaa1 — APPROVED** [review]

**Pull request merged**
