### PR TITLE
#265 image-placement fixed in testimonials

### PR DESCRIPTION
**Pull request by Annu117**
Image alignment in testimonials
#265

### CODE REVIEW

**Comment by Priyaaa1** [comment]
@Annu117 kindly add a comment mentioning the issue you resolved

**Comment by Annu117** [comment]
#265

**Comment by Annu117** [comment]
@Priyaaa1 done.

**Comment by Annu117** [comment]
@Priyaaa1 conflict resolved

**Comment by Annu117** [comment]
I didn't change the color, it was already pink.

**Comment by Priyaaa1** [comment]
@Annu117  This is the color now..

Screenshot (221)

**Comment by Annu117** [comment]
but these changes are done after my poll request.

**Comment by Annu117** [comment]
@Priyaaa1 plz check now.

**Comment by Annu117** [comment]
the hovering effect added does not align with the theme. Every hover effect is linear, and here, circular does not match.

**Comment by Annu117** [comment]
@Priyaaa1 plz merge.

**Comment by Annu117** [comment]
There was a bug in the outline blue color attached to the image. In the previous code and now, too. Also fixed that issue.

**Review by Priyaaa1 — APPROVED** [review]

**Comment by Priyaaa1** [comment]
@Annu117 it's looking nice :)

**Pull request merged**
