### PR TITLE
Deployed a Chatbot Fixes issue #111

### PR DESCRIPTION
**Pull request by Varnika2526**
1. Chat bot created in React.js and poisitioned in the bottom right corner,
2. More responses can be added to the chatbot, kindly view the ones added
3. Chatbot added matches the UI of the website
4. Named the chatbot as : "InvestIQ"
5. Type in "hi" or "mission of company" or " how to reach startConnect-Hub?" as a test input

https://github.com/Priyaaa1/StartConnect-Hub/assets/106170225/fe19d129-d57b-4205-94b4-be7e115b7e32

Fixes ISSUE : #111 
@Priyaaa1 Kindly review this PR

### CODE REVIEW

**Comment by Varnika2526** [comment]
@Priyaaa1 kindly review this PR #151

**Comment by Priyaaa1** [comment]
@Varnika2526 make small change, like you have written 'startConnect-Hub' in the test input. It is 'StartConnect-Hub'.
I will merge it.

**Comment by Varnika2526** [comment]
@Priyaaa1 I'll make the changes

**Comment by Varnika2526** [comment]
@Priyaaa1 I am making a new pull request and making the changes

**Comment by Varnika2526** [comment]
@Priyaaa1 kindly review PR #171 for the updated changes in the chatbot and addition of Log in button

**Pull request merged**
