### PR TITLE
Add start connect hub

### LINKED ISSUE #325: adding "STARTCONNECT" in the navigation bar
Currently, the company logo is displayed in the navigation bar, but the company's name is not mentioned beside it. While the logo is an important part of the brand identity, the company name is equally important for brand recognition, especially for new companies.

**Describe the solution you'd like**
I would like to add the name of the company besides the logo in the navigation bar this could enhance brand recognition and ensure that visitors immediately associate the website with its corporate identity. I believe this change will not only improve the user experience but also contribute to the branding of your website.

Screenshot 2024-05-30 233110

**Additional context**
As a first-time visitor, after scrolling through your website and reaching almost the footer, I wanted to see the name of the website. However, I found that the name is mentioned only at the very start. So, if I want to see the name, I have to scroll all the way back up. I believe this change will significantly improve the user experience and contribute to the branding of your website. I hope you will consider this suggestion.

I would request you to assign this issue to me and please add appropriate labels to it. Thank you

### PR DESCRIPTION
**Pull request by bhavya-taneja**
## Description:
i have added the name of the website i.e. Start Connect Hub in the navigation bar.

## Issue No:
Required Fixes #325 

## Type of change

[X] Other (specify): enhancement 

## Screenshots / videos (if applicable)
Attach any relevant screenshots or videos demonstrating the changes. Make sure to attach before & after screenshots in your PR.
image

## Checklist: 

- [X] I have made this change from my own.
- [X] I have taken help from some online resources.
- [X] My code follows the style guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generate no new warnings.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers and screenshots after making the changes.

## Additional Comments:
kindly tell if any changes are required.

### CODE REVIEW

**Comment by bhavya-taneja** [comment]
@Priyaaa1 i am not able to understand the issue in my PR why is it failing these checks can you please help me.

**Comment by Priyaaa1** [comment]
@bhavya-taneja there was some issue with the deployment of the website, maybe that's the reason.
Kindly resolve the conflicts.

**Comment by Priyaaa1** [comment]
@bhavya-taneja your changes increased the height of the navbar too much and the dark mode toggle is not there

**Comment by bhavya-taneja** [comment]
@Priyaaa1 i have done the changes required can you please check.
And regarding the dark mode toggle button its there and working but i guess there is some issue in the original repository as the toggle button is not visible in the originally deployed website as well 
original website
image
website after my changes
image

**Comment by Priyaaa1** [comment]
@bhavya-taneja there should be not any space between "Start" and "Connect", it's "StartConnect Hub". And kindly decrease it's font size. The alignment is not looking proper.

**Comment by bhavya-taneja** [comment]
@Priyaaa1 done a few changes..... kindly check it.

**Review by Priyaaa1 — APPROVED** [review]

**Pull request merged**
