### PR TITLE
[Fixes]; Security Issue #324

### PR DESCRIPTION
**Pull request by aryansharma220**
Fixes: #324 

image

Added the feature to hash the password and also can't be fetched from the console.

### CODE REVIEW

**Comment by aryansharma220** [comment]
@Priyaaa1 Please merge this pr. I have completed the task.

**Comment by Priyaaa1** [comment]
@aryansharma220 login page becomes blank, check preview

**Comment by aryansharma220** [comment]
> @aryansharma220 login page becomes blank, check preview

@Priyaaa1 Corrected it.

**Comment by Priyaaa1** [comment]
@aryansharma220 its not showing hashed password in the console

**Comment by Priyaaa1** [comment]
@aryansharma220 kindly resolve conflicts

**Comment by RishabhDhawad** [comment]
@aryansharma220  there are some merge conflicts in the following file, first resolve those and push your code again creating another PR as I am closing this one.

**Pull request closed without merging**
