### PR TITLE
Updated "Feedback Form"

### PR DESCRIPTION
**Pull request by MastanSayyad**
Hi @Priyaaa1  #444 

I have made the changes and push the files without pushing other dependencies to ensure Branch conflicts please try to merge this PR Before any other PRs and see if it is working properly.

image

### CODE REVIEW

**Comment by MastanSayyad** [comment]
@Priyaaa1 This should work, Please take a look and review it, Thank You

**Comment by MastanSayyad** [comment]
@Priyaaa1 This should work properly now, also i have one request if possible could you please give gssoc label for this PR so that it can also get considered for My Scores in the leaderboard, However we can go with this too, Thank You!

**Comment by Priyaaa1** [comment]
@MastanSayyad yeah it's working. Mention your respective issue so that you'll get points for that.

**Comment by MastanSayyad** [comment]
@Priyaaa1 issue #444

**Comment by Priyaaa1** [comment]
@MastanSayyad i don't know if on reverting the branch, your score will be considered for that or not. If it will be considered, then I can't give you level2 label for this PR as you have gained a lot score from my repository as per the guidelines.

**Comment by Priyaaa1** [comment]
@MastanSayyad if that PR score will not be considered, then I can label this PR.

**Comment by Priyaaa1** [comment]
@RishabhDhawad take a look.

**Comment by MastanSayyad** [comment]
> @MastanSayyad i don't know if on reverting the branch, your score will be considered for that or not. If it will be considered, then I can't give you level2 label for this PR as you have gained a lot score from my repository as per the guidelines.

Yeah, The new Guidelines are for documentation changes, not for technical and coding changes, It is stated that **any "techincal feature additions are excluded"** and no need to give level 2 label as I have just updated the email and my previous merged/reverted PR already have level 2 label, only add gssoc label so that this PR can get counted under GSSOC Program.

**Comment by MastanSayyad** [comment]
@Priyaaa1 and even if we follow the guidelines there is limit for 150 points and I have got 105 points total from this repository so I can still make the contributions and feature additions (tho this contribution **limit is only for spam of repeatative docs changes/non-technical/non-coding changes** and not for any coding/feature addition)

**Comment by Priyaaa1** [comment]
@MastanSayyad okay

**Review by Priyaaa1 — APPROVED** [review]

**Pull request merged**
