### PR TITLE
Implemented Real Email Functionality

### LINKED ISSUE #569: ➕Implement Real Email-Sending Functionality for Feedback Page !
Hello @Priyaaa1,

In the previous implementation #553,  the feedback submission form was showing a pop-up confirmation message **before the email was actually sent.**  
@Priyaaa1 , You pointed out that **the confirmation should only appear after the email has been successfully sent.**

### The Solution and Implementation:
I have implemented a real email-sending functionality using the **"emailjs-com"** library. This ensures that the success message is displayed only after the feedback email has been successfully sent.

#### Here's what I did:
- Integrated the **"emailjs-com" library** to handle email sending.
- Modified the feedback form **to send an email using "EmailJS" instead of opening the local mail application.**
- Updated the code to **display the success pop-up** message **only after the email is sent**.

You can see the implementation in the demo video attached.

https://github.com/Priyaaa1/StartConnect-Hub/assets/131389695/aa80859b-74d0-4d84-9879-e1b31ff88507

After that, Check The Mail On Given EmailId(for now it's my email id)
(For those Orange Circles, Please Read "Next Steps" Below )

image

<hr> 

### Next Steps:
Please review the demo and let me know if everything is okay. (if not please tell me I'll improve that)

If approved, **I'll need your EmailJS "Service_ID", "Template_ID", and "User_ID"** to complete the final setup. 
This will allow me **to update the template to use your project's official email [startconnecthub@gmail.com]** 
**(NOTE : I will not have access to it; full access will be given to you.)**

### Steps to Provide EmailJS Credentials to me :
1. Create a free account on EmailJS (if you don't have one). [Link to EmailJs](https://www.emailjs.com/) 
2. Set up a new email service and **get the Service_ID.**
3. Create an email template for the feedback form and **get the Template_ID.** (see example below)
' ' '
image
> 💡Circle (1)  On Right Side **(To Email)**
        - Enter the official email id of the star connect [startconnecthub@gmail.com].
> 💡Circle (2) On Right Side **(From Name)**
        - Enter "Star Connect Team" (for ex.) 

- And in other underlined places, Please keep it as I provided in the Screenshot. (**As they are the ID's from the code**)
' ' '

4. **Get your User_ID** from your EmailJS dashboard.

At the End - **Please Share these credentials with me so that I can update the code to use them.**

<hr> 

After that, Please merge that PR. I've gone through Many Official Documentations to Implement this Solution.
@Priyaaa1, Thank you for cooperating!

### PR DESCRIPTION
**Pull request by aslams2020**
Hey @Priyaaa1 ,
issue closes #569 

I have updated all the ID's **("Service_ID", "Template_ID", and "User_ID")** to your credentials.

**Here is the DEMO** - (if you have received the below feedback on the email-id, Then **functionality is working fine**.)

https://github.com/Priyaaa1/StartConnect-Hub/assets/131389695/c8ed5a46-fc34-4b44-bbf3-567f90ea7ee1

Thankyou for coordinating!
Please take a look

### CODE REVIEW

**Comment by aslams2020** [comment]
@Priyaaa1 Please Check

**Comment by Priyaaa1** [comment]
@aslams2020 it's not working as I haven't received any email.

**Comment by aslams2020** [comment]
@Priyaaa1 I Have made the changes. Now it is working fine
Hope you received the Testing Emails.

**Comment by Priyaaa1** [comment]
@aslams2020 
image
I got this.

**Comment by aslams2020** [comment]
@Priyaaa1, Ohok.. You need to add the ID's in the curly braces to your EmailJs Feedback Template.
(Because, The Texts in the Curly braces are the respective ID's from the code..)
Please Make Sure To Add Same Below - (Please add them as it is)

image


The above image is my Feedback Template.

**Comment by aslams2020** [comment]
@RishabhDhawad Please upgrade the level label as level2.

@Priyaaa1 Thank you for cooperating during this issue discussions

**Comment by aslams2020** [comment]
@Priyaaa1 did You made the necessary changes as above? 
Please tell me it's working fine or not.

**Pull request merged**
