### PR TITLE
Updated collaboration link

### PR DESCRIPTION
**Pull request by ayush-848**
Resolves issue #357 

image

### CODE REVIEW

**Comment by ayush-848** [comment]
@Priyaaa1 You can check it

**Comment by Priyaaa1** [comment]
@ayush-848 mention the issue you resolved.

**Comment by ayush-848** [comment]
> @ayush-848 mention the issue you resolved.

#357

**Review by Priyaaa1 — APPROVED** [review]

**Comment by Priyaaa1** [comment]
@ayush-848 the task you did is not of level 1, if there is gssoc label you'll get 1 point

**Comment by ayush-848** [comment]
> @ayush-848 the task you did is not of level 1, if there is gssoc label you'll get 1 point

Oh, ok

**Pull request merged**
