### PR TITLE
add hover effect on chaticon

### PR DESCRIPTION
**Pull request by HarshadaGirase**
fixes issue #312

### CODE REVIEW

**Comment by Priyaaa1** [comment]
@HarshadaGirase which issue have you solved? Kindly mention it.

**Comment by HarshadaGirase** [comment]
I worked on issue no. 312

**Comment by HarshadaGirase** [comment]
Actually I raised PR without getting issue assigned to me

**Comment by HarshadaGirase** [comment]
I have fixed the  issue could you merged it

**Pull request merged**
