### PR TITLE
Creating a Startups Page

### PR DESCRIPTION
**Pull request by avanimathur**
Issue #368 

@Priyaaa1 Please review the changes. 

image

This is under GSSOC'24.

### CODE REVIEW

**Comment by Priyaaa1** [comment]
@avanimathur the images of the startups aren't visible.

**Comment by avanimathur** [comment]
@Priyaaa1 I have made changes. Are the images visible now?

**Comment by Priyaaa1** [comment]
@avanimathur no

image

**Comment by RishabhDhawad** [comment]
@avanimathur  there are some merge conflicts in the file, first resolve those and push your code again creating another PR as I am closing this one.

**Pull request closed without merging**
