### PR TITLE
NAVBAR ENHANCEMENT

### PR DESCRIPTION
**Pull request by Manaswini123456**
The navbar has been changed with respect to the UI.

CHANGES DONE:
1. When hovering the text size has been increased and the option hovered upon is underlined.
2. Removal of the background color of the options.
3. Removal of the background color when hovering upon the logo and the login button.
4. For the light theme 'L' has been indicated, and for the dark theme 'D' has been indicated. 
5. Around the theme change circle a border has been added.

NORMAL STATE:
image

HOVER STATE:
image

DARK THEME CIRCLE:
image

ABOVE THE LOGO:
image

LOGIN BUTTON:
image

### CODE REVIEW

**Comment by Manaswini123456** [comment]
@Priyaaa1 Changes have been made, Kindly suggest changes if required.

**Comment by Manaswini123456** [comment]
@Priyaaa1 Kindly check the PR and let me know, if any changes are required.

**Comment by Priyaaa1** [comment]
@Manaswini123456 the light/dark mode toggle which is implemented in the website is good, also the navbar hover has been implemented 2-3 days ago.

**Comment by Manaswini123456** [comment]
@Priyaaa1 The hover is done with respect to the fact that, I have removed the background and on hover made the font size bigger and made it get underlined.

**Comment by Priyaaa1** [comment]
@Manaswini123456 check PR #427 , if he resolves the conflict I will merge that one, he modified navbar hover too.

**Comment by Manaswini123456** [comment]
@Priyaaa1 Ok.

**Comment by RishabhDhawad** [comment]
@Manaswini123456   there are some merge conflicts in the following file, first resolve those and push your code again creating another PR as I am closing this one.

**Comment by Manaswini123456** [comment]
@RishabhDhawad Will do the needful.

**Pull request closed without merging**
