### PR TITLE
"Updated for the web Theme"

### LINKED ISSUE #430: [Bug]: Dark & White Theme Change not working properly
**Describe the bug**
The  Dark and White Change Theme is not working properly text is not visible and components are not visible properly

**To Reproduce**
1. Go to [home](https://startconnect-hub.netlify.app/)
2. Scroll down to Footer and see along side and on different pages too
3. See error

**Expected behavior**
The  Dark and White Change Theme is not working properly text is not visible and components are not visible properly

**Screenshots**
image
image

**Desktop (please complete the following information):**
 - OS: Window
 - Browser:  Chrome
 - Version: 22

**Smartphone (please complete the following information):**
 - Device: PocoX3 Pro
 - OS: Android 12
 - Browser: Chrome
 - Version: 22

**Additional context**
@Priyaaa1 please assign me this issue under GSsOC label and good level

### PR DESCRIPTION
**Pull request by ManishBirthlia**
Hello @Priyaaa1 The Dark and White Change Theme was not working properly text is not visible and components are not visible properly which is fixed now here is the result of both 

Fixed #430 

# Dark Theme:-
image

# Light Theme:-
image

### CODE REVIEW

**Comment by Priyaaa1** [comment]
@ManishBirthlia kindly do not change the original theme, you've changed the blue color to lighter shade. The previous theme was looking better. And also, there's an issue with the GitHub icon in footer, it should be white without hover as it was before.

**Comment by ManishBirthlia** [comment]
> @ManishBirthlia kindly do not change the original theme, you've changed the blue color to lighter shade. The previous theme was looking better. And also, there's an issue with the GitHub icon in footer, it should be white without hover as it was before.

Okay then I will resolve those things too np

**Comment by ManishBirthlia** [comment]
@Priyaaa1 Now let me know that everything is as you wished for.

**Comment by ManishBirthlia** [comment]
Hello @Priyaaa1 please see all the changes and let me know if everything is correctly done.

**Comment by Priyaaa1** [comment]
@ManishBirthlia still the navbar color is not matching with the original theme.

**Comment by ManishBirthlia** [comment]
@Priyaaa1 you mean to say that even if Dark theme in On but the Navbar and Footer should not change right ??

**Comment by ManishBirthlia** [comment]
Hello, @Priyaaa1 I think now is everything is good and during this work, I also implemented Redux Store for managing a common State so please give e Level 3  of GSSOC please

**Comment by Priyaaa1** [comment]
@ManishBirthlia kindly look at the navbar, the navbar items are overlapping with the website name "StartConnect Hub".

**Pull request closed without merging**
