### PR TITLE
Made a clickable logo redirecting to the hero section of the page and added Social Links to the Website's Footer section

### PR DESCRIPTION
**Pull request by Varnika2526**
Earlier the responsiveness of the logo was static, I had added a code that redirects the user to the Hero section / Home Page of the website upon clicking , smoothly.

Here's a quick video on the update made

https://github.com/Priyaaa1/StartConnect-Hub/assets/106170225/9e62570c-72a1-408c-bd67-f881860132a6

issue number: #103 , #108 , #110  solved

Kindly review my PR @Priyaaa1

### CODE REVIEW

**Comment by Varnika2526** [comment]
@Priyaaa1 let me know for any other changes, Thank you

**Comment by Priyaaa1** [comment]
@Varnika2526 Footer is modified now, your code resolves issue #103 and #110
Don't modify footer

**Comment by Varnika2526** [comment]
sure

**Comment by Varnika2526** [comment]
@Priyaaa1 Kindly review

**Comment by Varnika2526** [comment]
@Priyaaa1 I had a query related to resolving conflicts, I wasn't sure as to what to do to resolve so i had deleted all the code that was creating issue, but now i think that it shouldn't be done, so i had copied the same code from the recent merged Footer.css and Footer.jsx, should i commit the new changes ir leave it as it is ?

**Pull request closed without merging**
