### PR TITLE
Implemented "Submitted Confirmation"  Pop-Up in Feedback Form

### LINKED ISSUE #546: Feature🌟 : Implement "Successfully Submitted Pop-Up" Confirmation in Feedback Form
Hi @Priyaaa1,
I want to request a feature -

To provide clear feedback upon form submission, I propose implementing a pop-up confirmation message for the feedback form. **This will inform users** that their feedback has been **successfully submitted** and prevent any confusion or repeated submissions.

Example Like this - 

image

**Expected Outcome**
- Users will see a confirmation message upon submitting the feedback form, ensuring they know their feedback has been received.
- This feature will improve user satisfaction by providing immediate and clear feedback on their submission.

I would like to take up this task and implement the feedback form submission pop-up. 
Could you please assign this issue to me?
Thank you!

### PR DESCRIPTION
**Pull request by aslams2020**
Hey @Priyaaa1,
issue closes #546 

I have implemented the pop up message after submitting the feedback form.

What i did - 
1. I **added the pop up notification** after submitting the feedback form
2. **added "pop-up close"** button at the top to close the popup notification
3. **added "Back to Home" button** to easily redirect to the home page after submitting the form.
4. also, i **tried my very best to match the color theme** of the website

as you can see - 
image

#### Video Preview 
Please take a look -

https://github.com/Priyaaa1/StartConnect-Hub/assets/131389695/52c8b000-9108-430b-9769-a38e1610839a

Please let me know if there's anything that need to be improve.
Thankyou!

### CODE REVIEW

**Comment by aslams2020** [comment]
@Priyaaa1

**Comment by aslams2020** [comment]
hey @Priyaaa1 ..could u Please take a look and review it.

**Comment by Priyaaa1** [comment]
@aslams2020 it is showing pop-up before the feedback email has been sent. It should be shown after it was sent.

**Comment by aslams2020** [comment]
> @aslams2020 it is showing pop-up before the feedback email has been sent. It should be shown after the email was sent.

@Priyaaa1 
For this We have to implement a real email-sending functionality using a library,  and also I have to raise a new issue, pls merge this PR and I'll work on the other issue for email sending functionality.

**Review by Priyaaa1 — APPROVED** [review]

**Comment by aslams2020** [comment]
@Priyaaa1, Thank you for merging the PR.
I'll work on the functionality ASAP.

**Comment by aslams2020** [comment]
Hey @Priyaaa1 , I have Implemented the functionality we discussed about. Please take a look at the issue I raised . ( #569 )
If everything's fine... I will Send the PR Request.
Thankyou!

**Pull request merged**
