### PR TITLE
valid email password changes as per issue #53

### PR DESCRIPTION
**Pull request by sayalisachin**
1. Email ID verification is enabled. 
2. Login and Signup alerts users to enter valid email id through keyshake animations and color changes of the input fields. 
3. Login Page allows users to show password by checking the tickbox.
4.  Signup Page checks if entered Password matches the confirmed password or not.( Alerts if not equal). 
5. Password is set to minimum 8 characters to ensure safety and viability (needs uppercase lowercase and a digit combination).

### CODE REVIEW

**Comment by Priyaaa1** [comment]
@sayalisachin Kindly resolve conflicts, i will merge it

**Comment by sayalisachin** [comment]
@Priyaaa1 any updates if it is conflicting or not

**Comment by ManishBirthlia** [comment]
I already solved this issue please assign me this and check my pull request and it will merge for sure.... check this pull request #295

**Comment by Priyaaa1** [comment]
@sayalisachin conflicts are there

**Comment by Priyaaa1** [comment]
@ManishBirthlia you will not get any points I guess if the issue you resolved wasn't assigned to you.

**Comment by ManishBirthlia** [comment]
@Priyaaa1 yes it is true that i will be not getting any points if you merge without assigning me the issue so please assign me this issue because they are taking too long to solve so i thought i should solve this

**Comment by Priyaaa1** [comment]
@sayalisachin kindly resolve conflicts as soon as possible

**Comment by RishabhDhawad** [comment]
Resolve conflicts in the below files
src/Components/Login/Login.css
src/Components/Login/Login.jsx
src/Components/Signup/Signup.jsx

**Pull request closed without merging**
