### PR TITLE
updated the chatbox

### PR DESCRIPTION
**Pull request by ayush-848**
Fixed issue #414 

I have updated the chatbox and also fixed the codebase bugs

image

### CODE REVIEW

**Comment by ayush-848** [comment]
@Priyaaa1 Please check it

**Comment by Priyaaa1** [comment]
@ayush-848 kindly resolve conflicts

**Comment by ayush-848** [comment]
@Priyaaa1 Conflicts are not showing from my side

**Comment by Priyaaa1** [comment]
@ayush-848 deploy preview isn't there

**Comment by ayush-848** [comment]
@Priyaaa1 Done

**Comment by Priyaaa1** [comment]
@ayush-848  the logo is not visible on clicking the chatbot button

**Comment by ayush-848** [comment]
> @ayush-848 the logo is not visible on clicking the chatbot button

@Priyaaa1 Sorry, i didn't get you

**Comment by ayush-848** [comment]
@Priyaaa1 now it is visible

**Comment by Priyaaa1** [comment]
@ayush-848 the chatbot is still not responsive for small screens

**Comment by ayush-848** [comment]
@Priyaaa1 check now

**Comment by ayush-848** [comment]
@Priyaaa1 check now, I have resolved all the conflicts

**Pull request merged**
