### PR TITLE
📝[Docs]: Changing of all issue templates and PR template

### LINKED ISSUE #642: 📝[Docs]: Changing of all issue templates and PR template
Wanted to change the layout of templates and pr.

Assign me under GSSOC

### PR DESCRIPTION
**Pull request by Anjaliavv51**
#642

## Description

Added new issue , PR template.

## Related Issues

[Cite any related issue(s) this pull request addresses. If none, simply state “None”]
- Closes #642 

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [X] Documentation update
- [ ] Other (specify): _______________

## Checklist

- [X] I have gone through the [contributing guide](https://github.com/Anishkagupta04/RAPIDOC-HEALTHCARE-WEBSITE-/)
- [X] I have updated my branch and synced it with project `main` branch before making this PR
- [X] I have performed a self-review of my code
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Priyaaa1 please review the PR.

**Comment by Anjaliavv51** [comment]
@Priyaaa1 please review the PR.

**Comment by Anjaliavv51** [comment]
@Priyaaa1 please review the PR.

**Comment by MastanSayyad** [comment]
@Anjaliavv51 The workflows work right?

**Comment by Anjaliavv51** [comment]
> @Anjaliavv51 The workflows work right?

Yes

**Pull request merged**
