### PR TITLE
Added ForgetPassword Section

### LINKED ISSUE #522: Add Forget Password Section
**Is your feature request related to a problem? Please describe.**
When we forget the password, there should be forget password option which will help us to solve the problem,

**Describe the solution you'd like**
I would like to add the forget password section in the login page which will help the user to get back their account

**Additional context**

Assign this to me under GSSoC'24.

### PR DESCRIPTION
**Pull request by MuraliDharan7**
## Description:
I have added Forget password section in the login page. 

##Screenshot:

https://github.com/Priyaaa1/StartConnect-Hub/assets/130668745/966f5979-f4a0-414e-884c-bd733b574afa

- Closes #522

### CODE REVIEW

**Comment by Priyaaa1** [comment]
@MuraliDharan7 your changes have also changed the position of the website name in the navbar. Kindly fix it.

**Comment by MuraliDharan7** [comment]
> @MuraliDharan7 your changes have also changed the position of the website name in the navbar. Kindly fix it.

https://github.com/Priyaaa1/StartConnect-Hub/assets/130668745/02744606-1b8b-4822-8d27-e80dedfa1a32

## Explanation
 
It seems it does not change the way you said. Check the above video whether it is changing or not. You can check out the video which I have tested in local machine.

**Comment by Priyaaa1** [comment]
@MuraliDharan7 the website name in the website is well positioned.
Look below, in the navbar

image

Your modification made it's position changed, that's what I'm saying to fix.

**Comment by MuraliDharan7** [comment]
image

Kindly check it once.

**Comment by Priyaaa1** [comment]
@MuraliDharan7 its showing blank page on clicking on reset

**Comment by MuraliDharan7** [comment]
> @MuraliDharan7 its showing blank page on clicking on reset

Can you Check it now?

**Comment by Priyaaa1** [comment]
@MuraliDharan7 it's working now

**Review by Priyaaa1 — APPROVED** [review]

**Pull request merged**
