### PR TITLE
Added "Feedback Form/Page" to "Star Connect Hub" Website

### LINKED ISSUE #444: 💡Add a Feedback Form/Page to "Star Connect Hub" Website
Hey @Priyaaa1 

I would like to add a **feedback form/page**

### Use Case
- User: Clicks on the "Give Feedback" button.
- System: Displays the feedback form as a popup.
- User: Fills out the feedback form, providing optional name and email, selecting the type of feedback, and entering comments.
- User: Clicks the "Submit" button on the form.
- System: Displays a confirmation message indicating the feedback was submitted successfully.
- User: Closes the feedback form popup.

To improve user experience and gather valuable insights from visitors, i suggest to add a feedback form/page to the "Star Connect Hub" website. This form will allow users to provide their opinions, report issues, and suggest improvements directly.
- **For example like this:**

image

Please assign this issue to me.

### PR DESCRIPTION
**Pull request by MastanSayyad**
Hey @Priyaaa1 | Closes #444

I have added **Feedback** form for the website, The feedback form allows users to submit their opinions directly from the application interface, enhancing our ability to collect valuable insights for future enhancements.

### Feature:

- A dedicated page for **"Feedback"** matching the website design theme.
- **Feedback form** of input fields for `name`, `email`, and `feedback`.
- A dynamic **Rating system** using emojis (😡, 😒, 😐, 😊,😁) to reflect **user sentiment** rating 1,2,3,4,5 respectively.
- Form submission functionality that sends user feedback directly to designated **Email**
- Navigation links in Navbar and Footer.

This feature integrates smoothly with our existing application architecture, maintaining consistency in user experience and design.

### Screenshots

- **Navigation Links in Navbar and Footer**

image

image

- **Feedback Form**

image

Users can select a rating from 1 to 5, each represented by a unique set of emojis ranging from less satisfied to highly satisfied.
😡 for **rating 1**
😒 for **rating 2**
😐 for **rating 3**
😊 for **rating 4**
😁 for **rating 5**
😶 for **No rating**

image

- **Redirect Email to designated** **Email**

image

### Overall Screen Record

https://github.com/Priyaaa1/StartConnect-Hub/assets/101971980/34461a51-7fe6-43e7-bd7c-e23278055630

Please take a look and review it, Thank You!!

### CODE REVIEW

**Comment by Priyaaa1** [comment]
@MastanSayyad deploy preview isn't there

**Comment by MastanSayyad** [comment]
@Priyaaa1 Try merging it and see if it is working correctly, as previously when we created Privacy policy, terms and conditions and other required pages it worked even after no preview. so you can try it.

**Review by Priyaaa1 — APPROVED** [review]

**Comment by MastanSayyad** [comment]
@Priyaaa1 Thank you for merging, Could you pls review and merge this PR also #440

**Comment by Priyaaa1** [comment]
@MastanSayyad  yeah I'll see. 
By your changes people can see my mail id, can you improve it ?

**Comment by MastanSayyad** [comment]
@Priyaaa1 then either you have to create a new separate Mail id for only start connect hub website like startconnecthub@gmail.com  or we have to remove the mail feature

**Comment by MastanSayyad** [comment]
should i make the changes to remove the mail functionality??

**Comment by MastanSayyad** [comment]
@Priyaaa1 To ensure that users do not see your email address while sending feedback, we have to initialize the backend server to handle the form submission and also send the email without exposing your email address in the frontend code. 

I will try to do it, it will take some more time as backend initialization needs to Set up a Node.js backend server using Express as our website don't have backend functionality and Axios in the frontend to send POST requests to the backend

**Comment by Priyaaa1** [comment]
@MastanSayyad yeah, created new mail id for the website. You can change mail id from old one to startconnecthub@gmail.com now, I will merge it.

**Pull request merged**
