### PR TITLE
solved issue -No hover effect on x , LinkedIn and Instagram icon in footer  |  #402

### PR DESCRIPTION
**Pull request by Prabhatyadav60**
This pull request includes the following changes: #402 

Hover Effect: Updated the hover effect  to improve user experience and visual consistency.
Footer Responsiveness: Made the footer responsive to ensure it displays correctly on various screen sizes and devices.
Details
before --

https://github.com/Priyaaa1/StartConnect-Hub/assets/133522303/34fed6d3-ea5b-4ff9-a6b2-1a102fdc3890

After---

https://github.com/Priyaaa1/StartConnect-Hub/assets/133522303/c339d150-6c54-4299-af6d-96d0cf656b51

also remove twitter and replace it with X
@Priyaaa1

### CODE REVIEW

**Comment by Priyaaa1** [comment]
The square boxes are not looking good

image

**Comment by Prabhatyadav60** [comment]
@Priyaaa1 removed box shadow effect.

**Comment by Priyaaa1** [comment]
@Prabhatyadav60 kindly resolve conflicts

**Comment by Prabhatyadav60** [comment]
@Priyaaa1 done ma'am ! conflicts resolved.

**Comment by Priyaaa1** [comment]
@Prabhatyadav60 your changes will change the footer alignment

**Pull request closed without merging**
