### PR TITLE
add testimonials head

### PR DESCRIPTION
**Pull request by root-0101**
Done the required changes regrading testimonials heading #51

### CODE REVIEW

**Comment by root-0101** [comment]
Please assign me the required labels for this PR

**Comment by root-0101** [comment]
Please assign me the required levels for this PR

**Comment by root-0101** [comment]
Please assign me the required levels for this successfully merged PR

**Comment by root-0101** [comment]
Hey @Priyaaa1  Please assign me the required levels for this successfully merged PR

**Comment by Priyaaa1** [comment]
@root-0101 the task was not of level1, level2 or level3. So I didn't put the label for it.
And if the issue has been merged without the label, it cannot give you points now

**Comment by Priyaaa1** [comment]
@root-0101 I have added gssoc label which may give you 1 point if counted

**Pull request merged**
